# Generated by Django 2.0 on 2018-10-01 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20181001_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='values',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.Value'),
        ),
    ]
