# Generated by Django 2.0 on 2018-10-03 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_transaction_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='values',
        ),
    ]
